package com.bloomtech.springboot.guidedproject.first_springboot_app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// This was generated by the Spring Initializr
// DO NOT CHANGE THIS


@SpringBootApplication // Tells the server this is a Spring Boot app
public class FirstSpringbootAppApplication {

	public static void main(String[] args) {
		// Start the server with this class
		SpringApplication.run(FirstSpringbootAppApplication.class, args);
	}

}
